---
- hosts: vagrant
  sudo: yes
  roles:
    - role: jsnshrmn.centos7
      tags: centos7
  pre_tasks:
    - include: pretasks.yml
      tags: pretasks

- hosts: ojs.vagrant.localdomain
  sudo: yes
  roles:
    - role: OULibraries.mariadb
      tags: mariadb
    - role: jsnshrmn.httpd24
      tags: httpd24
    - role: jsnshrmn.ojs
      tags: ojs
#    - role: OULibraries.ngrok
#      tags: ngrok

  pre_tasks:
    - name: /srv is a directory
      file: path=/srv state=directory mode=0755 force=yes
    - name: Check preconditions for running playbook.
      assert:
        that:
          - mariadb_root_pass is defined

# Go back and configure interactive users and devel settings
- hosts: vagrant
  roles:
    - role: jsnshrmn.users
      tags: users
